[package]
name = "config-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
bindgen = "0.72.0"
mem_cmp = "0.1.4"
serde = { version = "1.0.219", features=["derive"]}
winapi = "0.3.9"

[build-dependencies]
bindgen = "0.72.0"
cc = "1.2.27"

